import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    SECRET_KEY = '178745'
    SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:178745@localhost:5432/autotransport'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    GPS_UPDATE_INTERVAL = 60
    GPS_ACCURACY_THRESHOLD = 50
    NOTIFICATION_EMAIL = 'admin@example.com'
    NOTIFICATION_SMS_ENABLED = True
    NOTIFICATION_EMAIL_ENABLED = True
    REPORT_STORAGE_PATH = 'reports/'
    REPORT_FORMATS = ['pdf', 'xlsx', 'csv']
    MAINTENANCE_CHECK_INTERVAL = 7
    MAINTENANCE_NOTIFICATION_DAYS = 14
    FUEL_CONSUMPTION_THRESHOLD = 15
    SPEED_LIMIT = 90
    HARD_BRAKING_THRESHOLD = 0.5
    HARD_ACCELERATION_THRESHOLD = 0.5
    SESSION_TIMEOUT = 3600
    MAX_LOGIN_ATTEMPTS = 5
    PASSWORD_MIN_LENGTH = 8
    CACHE_TYPE = 'simple'
    CACHE_DEFAULT_TIMEOUT = 300 